config/routes.rb
TodoApp01::Application.routes.draw do

  get "/login" => 'sessions#new'
  get "/logout" => 'sessions#destroy'
  post "/sessions" => 'sessions#create'


# USERSCONTROLLER

resources :users

#


# TASKSCONTROLLER

root 'tasks#welcome'

get '/tasks' => 'tasks#index'

get '/tasks/new' => 'tasks#new', :as => "new_task"
post '/tasks' => 'tasks#create'


get '/tasks/:id' => 'tasks#show', :as => "task"
delete '/tasks/:id' => 'tasks#destroy'

get '/tasks/:id/edit' => 'tasks#edit', :as => "edit_task"
patch '/tasks/:id' => 'tasks#update'

delete '/tasks/:id/archive' => 'tasks#archive', :as => "archive_task"


# ARCHIVEDTASKS CONTROLLER

get '/archivedtasks' => 'archivedtasks#index'

delete '/archivedtasks/:id/undo' => 'archivedtasks#undo', :as => "undo_archivedtask"


end

app/models/archivedtask.rb
class Archivedtask < ActiveRecord::Base

belongs_to :user

end

app/models/task.rb
class Task < ActiveRecord::Base

validates_presence_of :content
belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

has_secure_password

validates_presence_of :username, :on => :create
validates_presence_of :email, :on => :create

# validates_presence_of :password, :on => :create
# validates_presence_of :password_confirmation, :on => :create

has_many :tasks
has_many :archivedtasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception





end

app/controllers/archivedtasks_controller.rb
class ArchivedtasksController < ApplicationController

def index
  user = User.find_by(id: session[:u_id])
  @archivedtasks = user.archivedtasks
end

def undo


  archivedtask = Archivedtask.find_by(id: params[:id])

  new_task = Task.new

  new_task.content = archivedtask.content
  new_task.owner = archivedtask.owner
  new_task.important = archivedtask.important
  new_task.user_id = archivedtask.user_id

  new_task.save
  archivedtask.destroy
  redirect_to archivedtasks_url

end





end

app/controllers/pages_controller.rb
class PagesController < ApplicationController



  def welcome

    reset_session
    # render :layout => false

  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController



def new
end




def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
    session[:u_id] = user.id
    redirect_to tasks_url, notice: "Hello, #{user.username}"

    else
    redirect_to login_url, notice: "Invalid email or password"
    end

end



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def welcome

    reset_session

  end



  def index


        user = User.find_by(id: session[:u_id])
        @tasks = user.tasks

        if params[:sort].present?
          @tasks = @tasks.where(important: true)

        end

        important_tasks = Array.new

        @tasks.each do |t|

          if t.important
            important_tasks << t
          end

        end

        @count_important_tasks = important_tasks.count

      end



  def new
  end


def create
   @t = Task.new
   @t.content = params["content"]
   @t.owner = params["owner"]
   @t.important = params["important"]

   user = User.find_by(id: session[:u_id])
   @t.user_id = user.id

  if @t.save
        respond_to do |format|
           format.html do
             redirect_to tasks_url
           end
           format.js
         end
  else
      @errors = @t.errors.full_messages
      render 'new'
  end

end


  def show
    task = Task.find_by(id: params[:id])
  end


def destroy
  @task = Task.find_by(id: params[:id])
  @task.destroy


    respond_to do |format|
      format.html do
        redirect_to tasks_url
      end
      format.js
    end





end


def edit
@task = Task.find_by(id: params[:id])

respond_to do |format|
      format.html do
        redirect_to tasks_url
      end
      format.js
    end

end


def update
@task = Task.find_by(id: params[:id])
@task.content = params["content"]
@task.owner = params["owner"]
@task.important = params["important"]
@task.save
# redirect_to tasks_url

    respond_to do |format|
      format.html do
        redirect_to tasks_url
      end
      format.js
    end

end


def archive
  @task = Task.find_by(id: params[:id])
  a = Archivedtask.new
  a.content = @task.content
  a.owner = @task.owner
  a.important = @task.important
  a.user_id = @task.user_id
  a.save
  @task.destroy
  # redirect_to tasks_url


    respond_to do |format|
      format.html do
        redirect_to tasks_url
      end
      format.js
    end




end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
end

def create
  @u = User.new
  @u.username = params[:username]
  @u.email = params[:email]
  @u.password = params[:password]
  @u.password_confirmation = params[:password_confirmation]

    if @u.save
      session[:u_id] = @u.id  # sign in!
      UserMailer.send_signup_welcome(@u).deliver
      redirect_to tasks_url
    else
      @errors = @u.errors.full_messages
      render 'tasks/welcome'
    end


end



def show
end

def destroy
end

def edit
end

def update
  u = User.find_by(:id => session[:id])
  u.username = params[:username]
  u.email = params[:email]
  u.password = params[:password]
  u.password_confirmation = params[:password_confirmation]
  u.save

  redirect_to tasks_url

end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archivedtasks_helper.rb
module ArchivedtasksHelper
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/archivedtasks/index.html.erb
<% if session[:u_id].present? %>

<!-- <h4>Number of smashed tasks: <%= @archivedtasks.count %></h4> -->

<table class = "table borderless">




<%  @archivedtasks.each do |a| %>

<tr id="archivedtask_<%= a.id %>">


<td class="center" id="done_task">

  <%= link_to '<i class="fa fa-check-circle-o fa-2x"></i>'.html_safe, undo_archivedtask_url(a.id), method: 'delete' %>


<!--   <button type="button" class="btn btn-success btn-sm btn-block"><%= link_to "UNDO", undo_archivedtask_url(a.id) %></button> -->

</td>


<td class="task" id="done_content"><%= a.content %></td>
<!-- <td><%= a.owner %></td>
<td><%= a.important %></td> -->

</tr>

<% end %>

</table>


<% else %>

<% redirect_to 'tasks/welcome' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TASKSMASHR</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>


<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">

<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">
    <!-- Bootstrap core CSS -->

 <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>


</head>



<body>

  <!-- Javascript Test Area -->

<script type="text/javascript">

$(document).ready(function() {
  $("a.fancybox").fancybox({
});
});


</script>




<!-- DISPLAY ONLY WHEN LOGIN IS CLICKED -->
    <div  id="lightbox" style="display:none">


        <div class="form-goup">
          <%= form_tag sessions_url do %>

              <h3><%= label_tag 'email', 'Email' %></h3>
              <%= text_field_tag 'email', nil, class: 'form-control sign-up' %>

              <h3><%= label_tag 'password', 'Password' %></h3>
              <%= password_field_tag 'password', nil, class: 'form-control sign-up' %>


              <%= submit_tag 'SMASH IT', class: 'form-control btn btn-default sign-up-button' %>
          <% end %>
        </div>

    </div>



<!-- END OF Javascript Test Area -->






<!-- TEST AREA FOR SMASH EFFECT -->



  <div class="row" id="smash" style="display:none">


        <h1>SMASHED<i class="fa fa-gavel"></i></h1>
        <h2>Find your smashed task in your archive.</h2>


  </div>






<!-- END OF SMASH EFFECT TEST AREA -->




  <div class="container">



  <header>
    <nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <% if session[:u_id].present? %>
    <a class="navbar-brand" href="/tasks">TASKSMASHR  <i class="fa fa-gavel"></i></a>
     <% else %>
    <a class="navbar-brand" href="/">TASKSMASHR  <i class="fa fa-gavel"></i></a>
    <% end %>

  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">

      <% if session[:u_id].present? %>
       <% user = User.find_by(:id => session[:u_id]) %>
       <li><%= link_to user.username , tasks_url %></li>
       <li><%= link_to "Archived Tasks", archivedtasks_url, class: "archive_link" %></li>
       <li><%= link_to "Logout", root_url %></li>

       <% else %>

       <li><%= link_to "Login", "#lightbox", :class => "fancybox" %></li>

      <% end %>



    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

  </header>


  <%= yield %>


  </div>


</body>
</html>

app/views/pages/hello.html.erb
<div class="welcome">

<h1>Hello my friend.</h1>

</div>

app/views/tasks/_edit_task.html.erb
<%= form_tag task_url(@task.id), method: 'patch', class: "form-inline", remote: true, authenticity_token: true do %>

      <% user = User.find_by(id: session[:u_id]) %>
      <%= hidden_field_tag :user_id, user.id  %>



      <div class="form-group" id="task_input">
        <label class="sr-only" for="content"></label>
        <%= text_field_tag 'content', @task.content, class: "form-control" %>
      </div>

<!--     <div class="form-group">
      <div class="checkbox">
      <label for = "important">IMPORTANT</label>
      <% if @task.important  %>
      <input id = "important" type = "checkbox" name = "important" checked = "checked" >
      <% else %>
      <input id = "important" type = "checkbox" name = "important">
      <% end %>
      </div>
    </div> -->

    <button type="submit" class="btn btn-default" id="update_action" style="display:none">Update task</button>



<% end %>

app/views/tasks/_new_task_input_form.html.erb
<%= form_tag tasks_url, method: 'post', class: "form-inline", id:"create_task_field", remote: true, authenticity_token: true do %>

      <% user = User.find_by(id: session[:u_id]) %>
      <%= hidden_field_tag :user_id, user.id  %>



      <div class="form-group" id="task_input">
        <label class="sr-only" for="content"></label>
        <%= text_field_tag 'content', nil, placeholder: "#{user.username}, what do you want to smash today?", class: "form-control" %>
      </div>

<!--     <div class="form-group">
      <div class="checkbox">
      <label for = "important">IMPORTANT</label>
      <input id = "important" type = "checkbox" name = "important">
      </div>
    </div> -->

    <button type="submit" class="btn btn-default" style="display:none">Add new task</button>





<% end %>

app/views/tasks/_task_row.html.erb
      <tr id="task_<%= task.id %>">

      <td class="center" id="smash_task">


       <!--  <button type="button" class="btn btn-success btn-sm btn-block"><%= link_to "SMASH", archive_task_url(task.id), method: :delete %></button> -->
        <%= link_to '<i class="fa fa-circle-o fa-2x"></i>'.html_safe, archive_task_url(task.id), method: :delete, remote: true, authenticity_token: true %>

      </td>

      <td class="task" id="task_content"><%= task.content %></td>

    <!--   <td><%= task.owner %></td> -->

      <!-- <td><%= task.important %></td> -->

      <td class="center">

  <!--  <button type="button" class="btn btn-danger btn-sm btn-block"><%= link_to "DELETE", task_url(task.id), method: 'delete' %></button> -->

             <%= link_to '<i class="fa fa-trash-o fa-2x"></i>'.html_safe, task_url(task.id), method: 'delete', remote: true, authenticity_token: true %>

      </td>


     <!--  <td class="center"><button type="button" class="btn btn-info btn-sm btn-block"><%= link_to "EDIT", edit_task_url(task.id) %></button></td> -->
     <td class="center">
     <%= link_to '<i class="fa fa-pencil-square fa-2x"></i>'.html_safe, edit_task_url(task.id), remote: true, authenticity_token: true %>
     </td>

      </tr>

app/views/tasks/archive.html.erb
<h1>Here comes the archive!</h1>

app/views/tasks/archive.js.erb
$("#task_<%= @task.id %>").remove();

// $(".smash").slideDown(750).delay(1000).slideUp(400);

// $("body").effect('bounce', {times:5}, 2000);

$("#smash").slideDown(750, function(){
  $(this).delay(300).effect('bounce', {times:30}, 2000).slideUp(1000);
});

app/views/tasks/archiveindex.html.erb
<div class="container">


<h1>MY TASK ARCHIVE</h1>

<h3><%= link_to "Go back home", root_url %></h3>

<h4>Number of archived tasks: <%= @archivedtasks.count %></h4>

<table class = "table table-bordered">

<tr>
<th>DONE?</th>
<th>TASK</th>
<th>OWNER</th>
<th>IMPORTANT</th>
</tr>


<%  @archivedtasks.each do |a| %>
<tr>
<td>DONE!</td>
<td><%= a.content %></td>
<td><%= a.owner %></td>
<td><%= a.important %></td>
</tr>

<% end %>

</table>

</div>

app/views/tasks/destroy.js.erb
$("#task_<%= @task.id %>").fadeOut(1000);
// $("body").effect('bounce', {times:5}, 2000);


// $(document).ready(function(){
//     $('div').click(function(){
//         $(this).effect('explode');
//     });
// });

app/views/tasks/edit.html.erb
<h2><%= @task.owner %>, update your task below.</h2>

<%= form_tag task_url(@task.id), method: 'patch' do %>

<div class="form-group">
<%= label_tag 'content', "Your Task" %>
<%= text_field_tag 'content', @task.content, class: "form-control" %>
</div>

<div class="form-group">
  <%= label_tag 'owner', "Task Owner" %>
  <%= text_field_tag 'owner', @task.owner, class: "form-control" %>
</div>

<div class="checkbox">
  <label for = "important">IMPORTANT</label>
    <% if @task.important  %>
      <input id = "important" type = "checkbox" name = "important" checked = "checked" >
    <% else %>
      <input id = "important" type = "checkbox" name = "important">
    <% end %>
</div>

<button type="submit" class="btn btn-default" id = "newtask">Update your task</button>

<% end %>

app/views/tasks/edit.js.erb
$("#task_<%= @task.id %>").hide();
$("#create_task_field").replaceWith('<%= j(render 'edit_task', :task => @task) %>');

// $("content")



// $("#update_action").on("click", function() {
//   $("#task_<%= @task.id %>").show();
// });

app/views/tasks/index.html.erb
<% if session[:u_id].present? %>


<script type="text/javascript">

$(document).ready(function() {
  $(".alert-info").fadeOut(3000, "linear");
});

// $(document).ready(function() {
//   $('.fa-circle-o').mouseenter(function() {
//     $('.fa-circle-o').hide();
//   });
// });




</script>



<% if notice.present? %>
<div class="alert alert-info"><%= notice %></div>
<% end %>

<!-- TASK INPUT LINE -->

<%= render "new_task_input_form" %>

<!-- ///////////////// -->




<div class="row">

  <div class="col-md-12">


      <table class = "table borderless" id = "task_table">


      <%  @tasks.each do |task| %>
      <tr id="task_<%= task.id %>">

      <td class="center" id="smash_task">


        <%= link_to '<i class="fa fa-circle-o fa-2x"></i>'.html_safe, archive_task_url(task.id), method: :delete, remote: true, authenticity_token: true %>

      </td>

      <td class="task" id="task_content"><%= task.content %></td>



     <!--  <td><%= task.important %></td> -->

      <td class="center">



             <%= link_to '<i class="fa fa-trash-o fa-2x"></i>'.html_safe, task_url(task.id), method: 'delete', remote: true, authenticity_token: true %>

      </td>


     <!--  <td class="center"><button type="button" class="btn btn-info btn-sm btn-block"><%= link_to "EDIT", edit_task_url(task.id) %></button></td> -->
     <td class="center">
     <%= link_to '<i class="fa fa-pencil-square fa-2x"></i>'.html_safe, edit_task_url(task.id), remote: true, authenticity_token: true %>
     </td>

      </tr>

      <% end %>

      </table>

  </div>
</div>







<% else %>

<% redirect_to 'tasks/welcome' %>

<% end %>

app/views/tasks/new.html.erb
<h2>SOMETHING NEW TO SMASH?</h2>

<% if @errors %>
  <% @errors.each do |msg| %>
  <h2><%= msg %></h2>
  <% end %>

<% end %>

<%= form_tag tasks_url, method: 'post' do %>

<div class="form-group">
  <%= label_tag 'content', "New Task" %>
  <%= text_field_tag 'content', nil, placeholder: "Enter your new task here...", class: "form-control" %>
</div>

<div class="form-group">
  <%= label_tag 'owner', "Task Owner" %>
  <%= text_field_tag 'owner', nil, placeholder: "Who has to smash that task?", class: "form-control" %>
</div>


<div class="checkbox">
<label for = "important">IMPORTANT</label>
<input id = "important" type = "checkbox" name = "important">
</div>

<button type="submit" class="btn btn-default" id = "newtask">Add new task</button>


<% end %>

app/views/tasks/show.html.erb
<!-- SHOW REST OF THE STUFF -->

<h1>TEST TEST TEST</h1>

app/views/tasks/update.js.erb
var content_update = $('input[name=content]')
$("#task_<%= @task.id %>").remove();


$('#task_input').replaceWith('<%= j(render 'new_task_input_form') %>');



$('tbody').append("<%= escape_javascript(render('task_row', :task => @task)) %>");



// ("<tr id="task_<%= @task.id %>"" + content_update + "</tr>")

app/views/tasks/welcome.html.erb
<!-- <div class="row">
  <div class="col-md-12">
    <h2>Sick of getting things done?<small>get ready for smashing your tasks</small></h2>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <%= form_tag new_user_url, method: 'get' do %>
    <button type="submit" class="btn btn-info" id = "welcome_button">CREATE A NEW ACCOUNT</button>
    <% end %>
  </div>

</div> -->

<script type="text/javascript">

$(document).ready(function() {
  $(".alert-danger").fadeOut(5000, "linear");
  $(".fa-circle-o").click(function(){
    $("#welcome_smash").slideDown(750, function(){
      $(this).delay(300).effect('bounce', {times:30}, 2000).slideUp(1000);
    });
  });
});


</script>


<div class="row">

      <div class="col-md-12">

      <% if @errors.present? %>
      <% @errors.each do |message|  %>
      <div class="alert alert-danger"><%= message %></div>
      <% end %>


      <% end %>



      </div>


</div>


<!-- DISPLAY ONLY WHEN LOGIN IS CLICKED -->
    <div id="sign_up" style="display:none">

      <div class="row">
        <h2>Signup</h2>
      </div>

        <div class="form-goup">
          <%= form_tag users_url, method: 'post' do %>
              <h3><%= label_tag 'username', 'User name' %></h3>
              <%= text_field_tag 'username', nil, class: 'form-control sign-up' %>

              <h3><%= label_tag 'email', 'Email' %></h3>
              <%= text_field_tag 'email', nil, class: 'form-control sign-up' %>

              <h3><%= label_tag 'password', 'Password' %></h3>
              <%= password_field_tag 'password', nil, class: 'form-control sign-up' %>

              <h3><%= label_tag 'password_confirmation', 'Password Confirmation' %></h3>
              <%= password_field_tag 'password_confirmation', nil, class: 'form-control sign-up' %>

              <%= submit_tag 'Create your account', class: 'form-control btn btn-default sign-up-button' %>
          <% end %>
        </div>

    </div>
<!-- END OF SIGNUP LIGHTBOX -->





  <div class="row" id="welcome_smash" style="display:none">


        <h1>SMASHED<i class="fa fa-gavel"></i></h1>
        <h2>This is how we smash!</h2>


  </div>
















<%= form_tag root_url, method: 'get' do %>


      <div class="form-group" id="task_input">
        <label class="sr-only" for="content"></label>
        <%= text_field_tag 'content', "Welcome to TASKSMASHR. In a few seconds you will add your tasks here.", class: "form-control" %>
      </div>

<!--     <div class="form-group">
      <div class="checkbox">
      <label for = "important">IMPORTANT</label>
      <input id = "important" type = "checkbox" name = "important">
      </div>
    </div> -->

    <button type="submit" class="btn btn-default" style="display:none">Add new task</button>





<% end %>








<div class="row">

  <div class="col-md-12">


      <table class = "table borderless" id = "task_table">


    <tr>

      <td class="center" id="smash_task">


        <i class="fa fa-circle-o fa-2x"></i>

      </td>

      <td class="task" id="task_content">Sign up for an account.</td>


      <td class="center">

             <i class="fa fa-trash-o fa-2x"></i>

      </td>

     <td class="center">
      <i class="fa fa-pencil-square fa-2x"></i>
     </td>

  </tr>

   <tr>

      <td class="center" id="smash_task">


        <i class="fa fa-circle-o fa-2x"></i>

      </td>

      <td class="task" id="task_content">Focus on 5 things you want to achieve today.</td>


      <td class="center">

             <i class="fa fa-trash-o fa-2x"></i>

      </td>

     <td class="center">
      <i class="fa fa-pencil-square fa-2x"></i>
     </td>

  </tr>


     <tr>

      <td class="center" id="smash_task">


        <i class="fa fa-circle-o fa-2x"></i>

      </td>

      <td class="task" id="task_content">Put them in your TASKSMASHR list.</td>


      <td class="center">

             <i class="fa fa-trash-o fa-2x"></i>

      </td>

     <td class="center">
      <i class="fa fa-pencil-square fa-2x"></i>
     </td>

  </tr>

   <tr>

      <td class="center" id="smash_task">


        <i class="fa fa-circle-o fa-2x"></i>

      </td>

      <td class="task" id="task_content">Smash your tasks step by step.</td>


      <td class="center">

             <i class="fa fa-trash-o fa-2x"></i>

      </td>

     <td class="center">
      <i class="fa fa-pencil-square fa-2x"></i>
     </td>

  </tr>

    <tr>

      <td class="center" id="smash_task">


        <i class="fa fa-circle-o fa-2x"></i>

      </td>

      <td class="task" id="task_content">Acomplish more by doing less.</td>


      <td class="center">

             <i class="fa fa-trash-o fa-2x"></i>

      </td>

     <td class="center">
      <i class="fa fa-pencil-square fa-2x"></i>
     </td>

  </tr>





      </table>

  </div>
</div>









<h1><%= link_to "Create your account!", "#sign_up", :class => "fancybox" %></li></h1>

app/views/users/edit.html.erb
<div class="col-md-3">

</div>



    <div class="col-md-6 sign-up-box">
      <% user = User.find_by(:id => session[:u_id]) %>
      <div class="row">
        <h2 class="sign-up-head"><%= user.username %>, edit your profile here.</h2>
      </div>

        <div class="form-goup">
          <%= form_tag user_url(user.id), method: 'patch' do %>
              <h3><%= label_tag 'username', 'User name' %></h3>
              <%= text_field_tag 'username', user.username, class: 'form-control sign-up' %>

              <h3><%= label_tag 'email', 'Email' %></h3>
              <%= text_field_tag 'email', user.email, class: 'form-control sign-up' %>

              <h3><%= label_tag 'password', 'New Password' %></h3>
              <%= password_field_tag 'password', nil, class: 'form-control sign-up' %>

              <h3><%= label_tag 'password_confirmation', 'Confirm new password' %></h3>
              <%= password_field_tag 'password_confirmation', nil, class: 'form-control sign-up' %>

              <%= submit_tag 'Update your account', class: 'form-control btn btn-default sign-up-button' %>
          <% end %>
        </div>

    </div>